package sdlc;

public class Quiz extends javax.swing.JFrame {
    Question[] questions;
    public Quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btngrp1 = new javax.swing.ButtonGroup();
        btngrp2 = new javax.swing.ButtonGroup();
        btngrp3 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        lblq1 = new javax.swing.JLabel();
        btn1o1 = new javax.swing.JRadioButton();
        btn1o2 = new javax.swing.JRadioButton();
        btn1o3 = new javax.swing.JRadioButton();
        btn1o4 = new javax.swing.JRadioButton();
        btnSubmit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setText("Quiz Time!");

        lblq1.setText("Question 1");

        btngrp1.add(btn1o1);
        btn1o1.setText("Option 1");
        btn1o1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1o1ActionPerformed(evt);
            }
        });

        btngrp1.add(btn1o2);
        btn1o2.setText("Option 2");

        btngrp1.add(btn1o3);
        btn1o3.setText("Option 3");

        btngrp1.add(btn1o4);
        btn1o4.setText("Option 4");

        btnSubmit.setText("Next");

        jButton1.setText("Previous");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblq1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn1o1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn1o2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn1o4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn1o3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton1)
                        .addGap(88, 88, 88)
                        .addComponent(btnSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(lblq1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn1o1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1o2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1o3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1o4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btn1o1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton btn1o1;
    private javax.swing.JRadioButton btn1o2;
    private javax.swing.JRadioButton btn1o3;
    private javax.swing.JRadioButton btn1o4;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup btngrp1;
    private javax.swing.ButtonGroup btngrp2;
    private javax.swing.ButtonGroup btngrp3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblq1;
    private javax.swing.JLabel title;
    // End of variables declaration                   
}

